"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LeakipediaRiskLevel;
(function (LeakipediaRiskLevel) {
    LeakipediaRiskLevel[LeakipediaRiskLevel["None"] = 0] = "None";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Low"] = 1] = "Low";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Medium"] = 2] = "Medium";
    LeakipediaRiskLevel[LeakipediaRiskLevel["High"] = 3] = "High";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Critical"] = 4] = "Critical";
})(LeakipediaRiskLevel = exports.LeakipediaRiskLevel || (exports.LeakipediaRiskLevel = {}));
var LeakipediaLeakedDataCategory;
(function (LeakipediaLeakedDataCategory) {
    // Critical
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CryptocurrencyData"] = 1000] = "CryptocurrencyData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CreditCardCVV"] = 1020] = "CreditCardCVV";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CreditCardNumbers"] = 1040] = "CreditCardNumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PlainPasswords"] = 1060] = "PlainPasswords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["AuthTokens"] = 1080] = "AuthTokens";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["KeyboardLogs"] = 1100] = "KeyboardLogs";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SensitivePhotos"] = 1120] = "SensitivePhotos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SensitiveVideos"] = 1140] = "SensitiveVideos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SexualOrientation"] = 1160] = "SexualOrientation";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SexualPractices"] = 1180] = "SexualPractices";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["FinancialData"] = 1200] = "FinancialData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PrivateMessages"] = 1220] = "PrivateMessages";
    // High
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["HashedPasswords"] = 2000] = "HashedPasswords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["DeviceInformation"] = 2020] = "DeviceInformation";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Purchases"] = 2040] = "Purchases";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Photos"] = 2060] = "Photos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Videos"] = 2080] = "Videos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Audios"] = 2100] = "Audios";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PartialCreditCardData"] = 2120] = "PartialCreditCardData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CrediticialStatus"] = 2140] = "CrediticialStatus";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Donations"] = 2160] = "Donations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["TaxationRecords"] = 2180] = "TaxationRecords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["UtilityBills"] = 2200] = "UtilityBills";
    // Medium
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PasswordHints"] = 3000] = "PasswordHints";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Addresses"] = 3020] = "Addresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PassportNumbers"] = 3040] = "PassportNumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["GovermentIssuedIDs"] = 3060] = "GovermentIssuedIDs";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["BiometricData"] = 3080] = "BiometricData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PhoneNumbers"] = 3100] = "PhoneNumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["EmailAddresses"] = 3120] = "EmailAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["AssetsInformation"] = 3140] = "AssetsInformation";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IncomeLevel"] = 3160] = "IncomeLevel";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Contacts"] = 3180] = "Contacts";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Health"] = 3200] = "Health";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PoliticalViews"] = 3220] = "PoliticalViews";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Habits"] = 3240] = "Habits";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Interests"] = 3260] = "Interests";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IMEINumbers"] = 3280] = "IMEINumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IMSINumbers"] = 3300] = "IMSINumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["WebsiteActivity"] = 3320] = "WebsiteActivity";
    //Low
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Name"] = 4000] = "Name";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Gender"] = 4020] = "Gender";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Birthdate"] = 4040] = "Birthdate";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Languages"] = 4060] = "Languages";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Nationalities"] = 4080] = "Nationalities";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Locations"] = 4100] = "Locations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Ethnicity"] = 4120] = "Ethnicity";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PhysicalAttributes"] = 4140] = "PhysicalAttributes";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Skills"] = 4160] = "Skills";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Religion"] = 4180] = "Religion";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["DeceasedDate"] = 4200] = "DeceasedDate";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SocialMediaProfiles"] = 4220] = "SocialMediaProfiles";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["UserNames"] = 4240] = "UserNames";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["LoginNames"] = 4260] = "LoginNames";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["ConsumerHabits"] = 4280] = "ConsumerHabits";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PaymentMethods"] = 4300] = "PaymentMethods";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Relationships"] = 4320] = "Relationships";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Family"] = 4340] = "Family";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Education"] = 4360] = "Education";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Occupations"] = 4380] = "Occupations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Employer"] = 4400] = "Employer";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IPAddresses"] = 4420] = "IPAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["MACAddresses"] = 4440] = "MACAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Others"] = 10000] = "Others";
})(LeakipediaLeakedDataCategory = exports.LeakipediaLeakedDataCategory || (exports.LeakipediaLeakedDataCategory = {}));
