"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var LeakipediaRiskLevel;
(function (LeakipediaRiskLevel) {
    LeakipediaRiskLevel[LeakipediaRiskLevel["None"] = 0] = "None";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Low"] = 1] = "Low";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Medium"] = 2] = "Medium";
    LeakipediaRiskLevel[LeakipediaRiskLevel["High"] = 3] = "High";
    LeakipediaRiskLevel[LeakipediaRiskLevel["Critical"] = 4] = "Critical";
})(LeakipediaRiskLevel = exports.LeakipediaRiskLevel || (exports.LeakipediaRiskLevel = {}));
var LeakipediaLeakedDataCategory;
(function (LeakipediaLeakedDataCategory) {
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CreditCardNumbers"] = 20] = "CreditCardNumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CreditCardCVV"] = 40] = "CreditCardCVV";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CryptocurrencyData"] = 60] = "CryptocurrencyData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["AuthTokens"] = 80] = "AuthTokens";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PlainPasswords"] = 100] = "PlainPasswords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["KeyboardLogs"] = 120] = "KeyboardLogs";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["HashedPasswords"] = 140] = "HashedPasswords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PasswordHints"] = 160] = "PasswordHints";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SexualOrientation"] = 180] = "SexualOrientation";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SexualPractices"] = 200] = "SexualPractices";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SensitivePhotos"] = 220] = "SensitivePhotos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PrivateMessages"] = 240] = "PrivateMessages";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PoliticalViews"] = 260] = "PoliticalViews";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Health"] = 280] = "Health";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["EmailAddresses"] = 300] = "EmailAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PhoneNumbers"] = 320] = "PhoneNumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Name"] = 340] = "Name";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["SocialSecurityNumber"] = 360] = "SocialSecurityNumber";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PassportNumber"] = 380] = "PassportNumber";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["BiometricData"] = 400] = "BiometricData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Gender"] = 420] = "Gender";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Birthdate"] = 440] = "Birthdate";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Addresses"] = 460] = "Addresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Languages"] = 480] = "Languages";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Nationalities"] = 500] = "Nationalities";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Locations"] = 520] = "Locations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Ethnicity"] = 540] = "Ethnicity";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PhysicalAttributes"] = 560] = "PhysicalAttributes";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Interests"] = 600] = "Interests";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Skills"] = 620] = "Skills";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Religion"] = 640] = "Religion";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["DigitalIdentities"] = 660] = "DigitalIdentities";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["UserNames"] = 680] = "UserNames";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["LoginNames"] = 700] = "LoginNames";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Photos"] = 720] = "Photos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Videos"] = 740] = "Videos";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Audios"] = 760] = "Audios";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["AssetsInformation"] = 780] = "AssetsInformation";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["ConsumerHabits"] = 800] = "ConsumerHabits";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["PaymentMethods"] = 820] = "PaymentMethods";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["CrediticialStatus"] = 840] = "CrediticialStatus";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["FinancialData"] = 860] = "FinancialData";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["TaxationRecords"] = 880] = "TaxationRecords";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Donations"] = 900] = "Donations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Contacts"] = 920] = "Contacts";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Relationships"] = 940] = "Relationships";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Family"] = 960] = "Family";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Education"] = 980] = "Education";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IncomeLevel"] = 1000] = "IncomeLevel";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Occupations"] = 1020] = "Occupations";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Employer"] = 1040] = "Employer";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IMEINumbers"] = 1060] = "IMEINumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IMSINumbers"] = 1080] = "IMSINumbers";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["IPAddresses"] = 1100] = "IPAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["MACAddresses"] = 1120] = "MACAddresses";
    LeakipediaLeakedDataCategory[LeakipediaLeakedDataCategory["Others"] = 2000] = "Others";
})(LeakipediaLeakedDataCategory = exports.LeakipediaLeakedDataCategory || (exports.LeakipediaLeakedDataCategory = {}));
